class RefundStatus:
    CREATED = "CREATED"
    CHECKING = "CHECKING"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    EXECUTING = "EXECUTING"
    PENDING = "PENDING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class RefundDecision:
    ALLOW = "ALLOW"
    BLOCK_DISPUTE = "BLOCK_DISPUTE"
    BLOCK_PRE_ALERT = "BLOCK_PRE_ALERT"
    BLOCK_DUPLICATE = "BLOCK_DUPLICATE"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"